import type { JwtAudience } from '@prisma/client';

/**
 * Canonical application topology (code + docs).
 * Clients consume the modular monolith. They do not own identity, orgs, money, or events.
 */
export type AppLifecycleStatus = 'IMPLEMENTED' | 'FOUNDATION' | 'FUNCTIONAL' | 'PLANNED' | 'DEFERRED';
export type AppSurface = 'mobile' | 'web';
export type AppBoundary = 'company' | 'partner' | 'customer' | 'onboarding';

export type ApplicationRecord = {
  id: string;
  path: string;
  currentPath: string | null;
  surface: AppSurface;
  name: string;
  purpose: string;
  targetUser: string;
  jwtAudiences: JwtAudience[];
  authorizationScope: string;
  boundary: AppBoundary;
  sharedApis: string[];
  dataOwnership: string;
  status: AppLifecycleStatus;
  futureStatus: string;
};

export const PARTNER_JWT_AUDIENCES: JwtAudience[] = ['customer', 'partner_applicant'];
export const COMPANY_JWT_AUDIENCES: JwtAudience[] = ['admin'];
export const CUSTOMER_JWT_AUDIENCES: JwtAudience[] = ['customer'];
export const DOCTOR_JWT_AUDIENCES: JwtAudience[] = ['doctor'];

export const APPLICATION_REGISTRY: ApplicationRecord[] = [
  {
    id: 'APP-CUS-M',
    path: 'apps/mobile',
    currentPath: 'apps/mobile',
    surface: 'mobile',
    name: 'Customer App',
    purpose: 'Commerce, bookings, and customer account for a Person acting as a customer.',
    targetUser: 'Customer (Person)',
    jwtAudiences: ['customer'],
    authorizationScope: 'self / customer cart-order-appointment in the selected country',
    boundary: 'customer',
    sharedApis: ['identity', 'catalog', 'cart', 'payment', 'order', 'logistics', 'appointments', 'consent'],
    dataOwnership: 'Customer Person; no seller, clinical-staff, or company-admin data',
    status: 'FOUNDATION',
    futureStatus: 'Commerce + account foundation; extend under authorized slices',
  },
  {
    id: 'APP-STORE-M',
    path: 'apps/mobile-store',
    currentPath: 'apps/mobile-store',
    surface: 'mobile',
    name: 'Store App',
    purpose: 'Location-scoped pharmacy/store operations (pick, receive, counter).',
    targetUser: 'Store / location staff of a company or partner pharmacy org',
    jwtAudiences: ['customer'],
    authorizationScope: 'organization + location membership; never global finance',
    boundary: 'partner',
    sharedApis: ['identity', 'catalog', 'inventory', 'order', 'logistics'],
    dataOwnership: 'Assigned store organization/location only',
    status: 'FUNCTIONAL',
    futureStatus: 'Extend pick/pack/offline queue under authorized store ops slices',
  },
  {
    id: 'APP-DEL-M',
    path: 'apps/mobile-delivery',
    currentPath: 'apps/mobile-delivery',
    surface: 'mobile',
    name: 'Delivery / Rider App',
    purpose: 'Assigned logistics jobs only (pickup, OTP/POD, exceptions).',
    targetUser: 'Delivery partner / rider',
    jwtAudiences: ['customer'],
    authorizationScope: 'assigned job + delivery organization; no clinical reports',
    boundary: 'partner',
    sharedApis: ['identity', 'logistics'],
    dataOwnership: 'Assigned shipments/jobs; no unrelated PII beyond job need',
    status: 'FUNCTIONAL',
    futureStatus: 'Mock carrier and sandbox earnings remain until live logistics/payout authorization',
  },
  {
    id: 'APP-DOC-M',
    path: 'apps/mobile-doctor',
    currentPath: 'apps/mobile-doctor',
    surface: 'mobile',
    name: 'Doctor App',
    purpose: 'Doctor workspace: profile, schedule, appointments, encounter foundation, video join.',
    targetUser: 'Doctor (clinical partner overlay on Person)',
    jwtAudiences: ['doctor'],
    authorizationScope: 'doctor profile + org membership + consent + country policy',
    boundary: 'partner',
    sharedApis: ['identity', 'doctor', 'appointments', 'consent', 'video'],
    dataOwnership: 'Own clinical relationships; never another doctor’s panel or vendor catalog',
    status: 'FOUNDATION',
    futureStatus:
      'R4 telemedicine sandbox implemented (mock default); production LiveKit NOT enabled; production telemedicine NOT ready; R5 Rx/refill attached under pack gates',
  },
  {
    id: 'APP-LAB-M',
    path: 'apps/mobile-lab',
    currentPath: 'apps/mobile-lab',
    surface: 'mobile',
    name: 'Lab Staff App',
    purpose: 'Assigned lab workflow (accession, processing). Not a generic partner app.',
    targetUser: 'Lab staff of a LAB organization',
    jwtAudiences: ['customer'],
    authorizationScope: 'lab organization + assigned work items',
    boundary: 'partner',
    sharedApis: ['identity', 'lab'],
    dataOwnership: 'Assigned lab org workflow; no other lab',
    status: 'FUNCTIONAL',
    futureStatus: 'R7-D accession and processing on mobile; pathology remains web-first',
  },
  {
    id: 'APP-PHE-M',
    path: 'apps/mobile-phlebotomist',
    currentPath: 'apps/mobile-phlebotomist',
    surface: 'mobile',
    name: 'Phlebotomist App',
    purpose: 'Assigned sample-collection jobs and chain of custody.',
    targetUser: 'Phlebotomist',
    jwtAudiences: ['customer'],
    authorizationScope: 'assigned collection jobs; no unrelated patients',
    boundary: 'partner',
    sharedApis: ['identity', 'lab', 'logistics'],
    dataOwnership: 'Assigned job patients only',
    status: 'FUNCTIONAL',
    futureStatus: 'R7-C field journey; no GPS unless pack requires; accession remains R7-D+',
  },
  {
    id: 'APP-CUS-W',
    path: 'apps/web-customer',
    currentPath: 'apps/web-customer',
    surface: 'web',
    name: 'Customer Web',
    purpose: 'Responsive customer storefront and account.',
    targetUser: 'Customer (Person)',
    jwtAudiences: ['customer'],
    authorizationScope: 'self / customer country cart-order-appointment',
    boundary: 'customer',
    sharedApis: ['identity', 'catalog', 'cart', 'payment', 'order', 'logistics', 'appointments'],
    dataOwnership: 'Customer Person',
    status: 'FOUNDATION',
    futureStatus: 'Account foundation added; extend content/care under authorized slices',
  },
  {
    id: 'APP-STORE-W',
    path: 'apps/web-store',
    currentPath: 'apps/web-store',
    surface: 'web',
    name: 'Store Web',
    purpose: 'Store/location operations on web.',
    targetUser: 'Store staff',
    jwtAudiences: ['customer'],
    authorizationScope: 'organization + location',
    boundary: 'partner',
    sharedApis: ['identity', 'catalog', 'inventory', 'order'],
    dataOwnership: 'Assigned store org/location',
    status: 'FUNCTIONAL',
    futureStatus: 'Location-scoped inventory/order facade; not company ERP',
  },
  {
    id: 'APP-VEND-W',
    path: 'apps/web-vendor',
    currentPath: 'apps/web-vendor',
    surface: 'web',
    name: 'Vendor Web',
    purpose: 'Seller catalog, inventory, orders, shipments, own settlements.',
    targetUser: 'Vendor organization operators',
    jwtAudiences: ['customer'],
    authorizationScope: 'own seller organization; never company finance/admin',
    boundary: 'partner',
    sharedApis: ['identity', 'catalog', 'inventory', 'order', 'logistics', 'finance (own payables)'],
    dataOwnership: 'Own seller org offers/orders/settlements',
    status: 'FOUNDATION',
    futureStatus: 'Extend seller ops; no vendor mobile unless later authorized',
  },
  {
    id: 'APP-DOC-W',
    path: 'apps/web-doctor',
    currentPath: 'apps/web-doctor',
    surface: 'web',
    name: 'Doctor Web',
    purpose: 'Doctor workspace on web (profile, schedule, appointments, video).',
    targetUser: 'Doctor',
    jwtAudiences: ['doctor'],
    authorizationScope: 'doctor + relationship + consent + policy',
    boundary: 'partner',
    sharedApis: ['identity', 'doctor', 'appointments', 'consent', 'video'],
    dataOwnership: 'Own clinical panel',
    status: 'FOUNDATION',
    futureStatus:
      'R4 telemedicine sandbox implemented (mock default); production LiveKit NOT enabled; production telemedicine NOT ready; R5 prescribing/refill under pack gates',
  },
  {
    id: 'APP-LAB-W',
    path: 'apps/web-lab',
    currentPath: 'apps/web-lab',
    surface: 'web',
    name: 'Lab Web',
    purpose: 'Lab organization operations.',
    targetUser: 'Lab owner/manager/staff',
    jwtAudiences: ['customer'],
    authorizationScope: 'lab organization + assigned workflow',
    boundary: 'partner',
    sharedApis: ['identity', 'partner', 'catalog', 'lab'],
    dataOwnership: 'Own lab org',
    status: 'FOUNDATION',
    futureStatus:
      'R7-A diagnostics foundation + lab partner/catalog gates implemented; booking/CoC/pathology NOT started; no LIS/HIS',
  },
  {
    id: 'APP-RAD-W',
    path: 'apps/web-radiology',
    currentPath: 'apps/web-radiology',
    surface: 'web',
    name: 'Radiology Web',
    purpose: 'Imaging center organization operations (foundation).',
    targetUser: 'Imaging center owner/manager/staff',
    jwtAudiences: ['customer'],
    authorizationScope: 'imaging center organization + assigned workflow',
    boundary: 'partner',
    sharedApis: ['identity', 'partner', 'catalog', 'radiology'],
    dataOwnership: 'Own imaging center org',
    status: 'FOUNDATION',
    futureStatus:
      'R8-A–F sandbox imaging loop: booking, acquisition, radiologist interpretation, digital report. PACS/DICOM/image viewer missing.',
  },
  {
    id: 'APP-RADL-W',
    path: 'apps/web-radiologist',
    currentPath: 'apps/web-radiologist',
    surface: 'web',
    name: 'Radiologist Web',
    purpose: 'Assigned imaging interpretation cases only (R8-D).',
    targetUser: 'Radiologist',
    jwtAudiences: ['customer'],
    authorizationScope: 'imaging center org + assigned cases; no unrelated cases',
    boundary: 'partner',
    sharedApis: ['identity', 'radiology/interpretation'],
    dataOwnership: 'Assigned imaging interpretation cases',
    status: 'IMPLEMENTED',
    futureStatus: 'R8-D/E worklist, draft, verify SoD, customer publication. No DICOM viewer.',
  },
  {
    id: 'APP-PATH-W',
    path: 'apps/web-pathologist',
    currentPath: 'apps/web-pathologist',
    surface: 'web',
    name: 'Pathologist Web',
    purpose: 'Assigned diagnostic cases only.',
    targetUser: 'Pathologist',
    jwtAudiences: ['customer'],
    authorizationScope: 'lab org + assigned cases; no unrelated cases',
    boundary: 'partner',
    sharedApis: ['identity', 'lab/pathology'],
    dataOwnership: 'Assigned cases',
    status: 'IMPLEMENTED',
    futureStatus: 'Pathology worklist, verify, publish in sandbox',
  },
  {
    id: 'APP-OPS-W',
    path: 'apps/web-logistics',
    currentPath: 'apps/web-logistics',
    surface: 'web',
    name: 'Logistics / Ops Web',
    purpose: 'Company or contracted-ops shipment exceptions and job board.',
    targetUser: 'Company logistics ops or contracted delivery-org ops',
    jwtAudiences: ['admin', 'customer'],
    authorizationScope: 'company logistics permissions OR delivery org membership; not clinical payload',
    boundary: 'company',
    sharedApis: ['identity', 'logistics', 'order'],
    dataOwnership: 'Scoped shipments; company staff still country/region bound',
    status: 'FUNCTIONAL',
    futureStatus: 'Dedicated ops console on port 3011; shares admin logistics APIs',
  },
  {
    id: 'APP-AFF-W',
    path: 'apps/web-affiliate',
    currentPath: 'apps/web-affiliate',
    surface: 'web',
    name: 'Affiliate Web',
    purpose: 'Affiliate attribution and own earnings. Web primary; companion mobile is APP-AFF-M.',
    targetUser: 'Affiliate organization operators',
    jwtAudiences: ['customer'],
    authorizationScope: 'own affiliate organization / own person earnings; never company finance admin',
    boundary: 'partner',
    sharedApis: ['identity', 'finance (own liabilities)'],
    dataOwnership: 'Own affiliate liabilities',
    status: 'IMPLEMENTED',
    futureStatus: 'R12-D affiliate web with referral codes, links, clicks, and earnings visibility.',
  },
  {
    id: 'APP-AFF-M',
    path: 'apps/mobile-affiliate',
    currentPath: 'apps/mobile-affiliate',
    surface: 'mobile',
    name: 'Affiliate Mobile',
    purpose:
      'Affiliate partner mobile: dashboard, referral codes/links, commissions, statement, payout/KYC status (read-only). Reuses me/affiliate APIs; no live payout execution.',
    targetUser: 'Affiliate organization operators',
    jwtAudiences: ['customer'],
    authorizationScope: 'own affiliate organization / own person earnings; never company finance admin',
    boundary: 'partner',
    sharedApis: ['identity', 'finance (own liabilities)', 'notifications', 'support'],
    dataOwnership: 'Own affiliate liabilities; no cross-affiliate data',
    status: 'FUNCTIONAL',
    futureStatus:
      'S155 mobile companion of web-affiliate; production payout/KYC providers remain EXTERNAL_GATED (S149/S150)',
  },
  {
    id: 'APP-ADM-W',
    path: 'apps/web-admin',
    currentPath: 'apps/web-admin',
    surface: 'web',
    name: 'Admin / ERP Web',
    purpose: 'Company control plane. Architecture, navigation, and authorization boundaries only for unbuilt domains.',
    targetUser: 'Company staff with explicit company membership + admin JWT',
    jwtAudiences: ['admin'],
    authorizationScope: 'company hierarchy (platform/region/country/legal entity) + named permissions',
    boundary: 'company',
    sharedApis: [
      'identity',
      'partner',
      'policy',
      'catalog',
      'inventory',
      'payment',
      'order',
      'logistics',
      'finance',
      'doctor',
      'appointments',
    ],
    dataOwnership: 'Company-scoped configuration and operations; partners never receive this client as admins',
    status: 'FOUNDATION',
    futureStatus: 'Governance read-only foundation added; grow module-by-authorization',
  },
  {
    id: 'APP-JOIN-W',
    path: 'apps/web-join',
    currentPath: 'apps/web-join',
    surface: 'web',
    name: 'Partner Join Web',
    purpose: 'Public + applicant onboarding only. Not an operations console.',
    targetUser: 'Partner applicants',
    jwtAudiences: ['partner_applicant'],
    authorizationScope: 'own application + KYC upload; never company roles',
    boundary: 'onboarding',
    sharedApis: ['identity', 'partner application'],
    dataOwnership: 'Own application records',
    status: 'FUNCTIONAL',
    futureStatus: 'Public join remains pack-gated; legal document lists are human-owned',
  },
];

export const FORBIDDEN_APPLICATIONS = [
  'Generic Partner App',
  'Per-country forked apps',
  'Independent customer_users / doctor_users / vendor_users / affiliate_users stores',
] as const;

export const SHARED_KERNELS = [
  'identity',
  'organization/partner',
  'country/region/legal-entity scope',
  'permission/RBAC',
  'audit/security events',
  'policy packs',
  'modular API',
  'outbox/event foundation',
  'financial kernel',
  'logistics kernel',
  'ui-kit tokens',
] as const;

export function applicationsByStatus(status: AppLifecycleStatus): ApplicationRecord[] {
  return APPLICATION_REGISTRY.filter((app) => app.status === status);
}

export function applicationByPath(path: string): ApplicationRecord | undefined {
  return APPLICATION_REGISTRY.find((app) => app.path === path || app.currentPath === path);
}
