import { Injectable, Logger } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { uuidv7 } from '@world-pharma/shared';
import { PrismaService } from '../app/prisma.service';

export type SecurityEventType =
  | 'USER_REGISTERED'
  | 'OTP_REQUESTED'
  | 'OTP_VERIFIED'
  | 'OTP_FAILED'
  | 'LOGIN_SUCCESS'
  | 'LOGIN_FAILED'
  | 'SESSION_CREATED'
  | 'SESSION_REVOKED'
  | 'LOGOUT'
  | 'LOGOUT_ALL'
  | 'REFRESH_TOKEN_ROTATED'
  | 'REFRESH_TOKEN_REUSE_DETECTED'
  | 'MFA_ENABLED'
  | 'MFA_DISABLED'
  | 'ACCOUNT_LOCKED'
  | 'RATE_LIMITED'
  | 'SUSPICIOUS_REQUEST'
  | 'UNAUTHORIZED_ACCESS_ATTEMPT'
  | 'PRIVILEGE_DENIED'
  | 'COUNTRY_POLICY_CREATED'
  | 'COUNTRY_POLICY_VALIDATED'
  | 'COUNTRY_POLICY_PUBLISHED'
  | 'COUNTRY_POLICY_RETIRED'
  | 'COUNTRY_POLICY_ROLLED_BACK'
  | 'PARTNER_CREATED'
  | 'PARTNER_APPLICATION_CREATED'
  | 'PARTNER_APPLICATION_SUBMITTED'
  | 'PARTNER_STATUS_CHANGED'
  | 'KYC_CREATED'
  | 'KYC_SUBMITTED'
  | 'KYC_DOCUMENT_UPLOADED'
  | 'KYC_DOCUMENT_VIEWED'
  | 'KYC_DOCUMENT_DOWNLOADED'
  | 'KYC_DOCUMENT_VERIFIED'
  | 'KYC_DOCUMENT_REJECTED'
  | 'PARTNER_INVITATION_CREATED'
  | 'PARTNER_INVITATION_ACCEPTED'
  | 'PARTNER_INVITATION_REVOKED'
  | 'ORGANIZATION_CREATED'
  | 'ORGANIZATION_MEMBER_ADDED'
  | 'ORGANIZATION_MEMBER_REMOVED'
  | 'DOCTOR_PROFILE_CREATED'
  | 'DOCTOR_PROFILE_UPDATED'
  | 'DOCTOR_CREDENTIAL_SUBMITTED'
  | 'DOCTOR_CREDENTIAL_REVIEWED'
  | 'CONSENT_GRANTED'
  | 'CONSENT_REVOKED'
  | 'APPOINTMENT_CREATED'
  | 'APPOINTMENT_CONFIRMED'
  | 'APPOINTMENT_RESCHEDULED'
  | 'APPOINTMENT_CANCELLED'
  | 'APPOINTMENT_CHECKED_IN'
  | 'ENCOUNTER_STARTED'
  | 'ENCOUNTER_COMPLETED'
  | 'VIDEO_SESSION_CREATED'
  | 'VIDEO_SESSION_READY'
  | 'VIDEO_PARTICIPANT_JOINED'
  | 'VIDEO_PARTICIPANT_LEFT'
  | 'VIDEO_SESSION_STARTED'
  | 'VIDEO_SESSION_ENDED'
  | 'VIDEO_SESSION_FAILED'
  | 'INVENTORY_RECEIVED'
  | 'INVENTORY_ADJUSTED'
  | 'INVENTORY_TRANSFERRED'
  | 'MARKETPLACE_SELLER_ATTESTED'
  | 'MARKETPLACE_SELLER_ACCEPTED'
  | 'MARKETPLACE_SELLER_BLOCKED'
  | 'MARKETPLACE_SELLER_ACCEPTANCE_RESET'
  | 'LAB_PARTNER_ATTESTED'
  | 'LAB_PARTNER_ACCEPTED'
  | 'LAB_PARTNER_BLOCKED'
  | 'LAB_PARTNER_ACCEPTANCE_RESET'
  | 'IMAGING_PARTNER_ATTESTED'
  | 'IMAGING_PARTNER_ACCEPTED'
  | 'IMAGING_PARTNER_BLOCKED'
  | 'IMAGING_PARTNER_ACCEPTANCE_RESET'
  | 'LAB_BOOKING_CREATED'
  | 'LAB_BOOKING_CONFIRMED'
  | 'LAB_BOOKING_CANCELLED'
  | 'LAB_BOOKING_PAYMENT_FAILED'
  | 'IMAGING_BOOKING_CREATED'
  | 'IMAGING_BOOKING_CONFIRMED'
  | 'IMAGING_BOOKING_CANCELLED'
  | 'IMAGING_BOOKING_PAYMENT_FAILED'
  | 'IMAGING_STUDY_CREATED'
  | 'IMAGING_STUDY_ASSIGNED'
  | 'IMAGING_ACQUISITION_STARTED'
  | 'IMAGING_ACQUISITION_COMPLETED'
  | 'IMAGING_ACQUISITION_FAILED'
  | 'IMAGING_REPORT_DRAFT_CREATED'
  | 'IMAGING_REPORT_ASSIGNED'
  | 'IMAGING_REPORT_FINDINGS_ENTERED'
  | 'IMAGING_REPORT_SUBMITTED_VERIFY'
  | 'IMAGING_REPORT_VERIFIED'
  | 'IMAGING_REPORT_PUBLISHED'
  | 'IMAGING_REPORT_AMENDED'
  | 'IMAGING_REPORT_CUSTOMER_VIEW'
  | 'LAB_SAMPLE_ASSIGNED'
  | 'LAB_SAMPLE_PHLEBOTOMIST_ASSIGNED'
  | 'LAB_SAMPLE_COC_TRANSITION'
  | 'LAB_REPORT_DRAFT_CREATED'
  | 'LAB_REPORT_RESULTS_ENTERED'
  | 'LAB_REPORT_SUBMITTED_VERIFY'
  | 'LAB_REPORT_VERIFIED'
  | 'LAB_REPORT_PUBLISHED'
  | 'LAB_REPORT_AMENDED'
  | 'LAB_REPORT_CUSTOMER_VIEW'
  | 'PHYSICAL_REPORT_REQUESTED'
  | 'PHYSICAL_REPORT_ACCEPTED'
  | 'PHYSICAL_REPORT_PREPARING'
  | 'PHYSICAL_REPORT_PACKED'
  | 'PHYSICAL_REPORT_DISPATCHED'
  | 'PHYSICAL_REPORT_DELIVERED'
  | 'PHYSICAL_REPORT_FAILED'
  | 'PHYSICAL_REPORT_CANCELLED'
  | 'COMPANY_MEMBERSHIP_GRANTED'
  | 'PRIVILEGE_GRANT_REQUESTED'
  | 'PRIVILEGE_ESCALATION_DENIED'
  | 'DUAL_CONTROL_REJECTED'
  | 'BREAK_GLASS_OPENED'
  | 'BREAK_GLASS_HEALTH_REVIEWED'
  | 'CARE_NAV_SESSION_CREATED'
  | 'CARE_NAV_ANSWER_RECORDED'
  | 'CARE_NAV_TRIAGE_COMPLETED'
  | 'CARE_NAV_MATCH_COMPLETED'
  | 'CARE_NAV_HANDOFF_BOOKED'
  | 'CARE_NAV_SESSION_TERMINATED'
  | 'CARE_NAV_OVERRIDE_APPLIED'
  | 'CMS_CONTENT_CREATED'
  | 'CMS_CONTENT_UPDATED'
  | 'CMS_CONTENT_SUBMITTED'
  | 'CMS_CONTENT_PUBLISHED'
  | 'CMS_CONTENT_ARCHIVED'
  | 'CMS_ASSET_UPLOADED'
  | 'SUPPORT_TICKET_CREATED'
  | 'SUPPORT_TICKET_ASSIGNED'
  | 'SUPPORT_TICKET_STATUS_CHANGED'
  | 'SUPPORT_TICKET_MESSAGE_ADDED'
  | 'CRM_CUSTOMER_VIEW'
  | 'MARKETING_PREF_CHANGED'
  | 'CONVERSION_EVENT_RECORDED'
  | 'ANALYTICS_QUERY'
  | 'CRM_SEGMENT_CREATED'
  | 'CRM_SEGMENT_UPDATED'
  | 'CRM_CAMPAIGN_CREATED'
  | 'CRM_CAMPAIGN_UPDATED'
  | 'CRM_CAMPAIGN_SCHEDULED'
  | 'CRM_CAMPAIGN_SENT'
  | 'PROMO_CAMPAIGN_CREATED'
  | 'PROMO_CAMPAIGN_UPDATED'
  | 'PROMO_CAMPAIGN_PUBLISHED'
  | 'AFFILIATE_REFERRAL_CREATED'
  | 'WISHLIST_ITEM_ADDED'
  | 'WISHLIST_ITEM_REMOVED'
  | 'LOYALTY_PROGRAM_CREATED'
  | 'LOYALTY_PROGRAM_UPDATED'
  | 'LOYALTY_LEDGER_ENTRY_RECORDED'
  | 'PRODUCT_REVIEW_SUBMITTED'
  | 'PRODUCT_REVIEW_MODERATED'
  | 'PRODUCT_QUESTION_SUBMITTED'
  | 'PRODUCT_QUESTION_MODERATED'
  | 'PERSONALIZATION_EVENT_RECORDED'
  | 'CRM_AUTOMATION_RUN'
  | 'SEARCH_REINDEX_REQUESTED'
  | 'CLINICAL_SEARCH_QUERY'
  | 'HEALTH_ARTIFACT_READ'
  | 'HEALTH_DOCUMENT_UPLOADED'
  | 'APP_AUDIENCE_DENIED';

@Injectable()
export class SecurityEventsService {
  private readonly logger = new Logger(SecurityEventsService.name);

  constructor(private readonly prisma: PrismaService) {}

  async emit(input: {
    type: SecurityEventType;
    outcome: 'success' | 'failure';
    personId?: string;
    sessionId?: string;
    requestId?: string;
    ipHash?: string;
    metadata?: Record<string, unknown>;
  }): Promise<void> {
    this.logger.log(
      JSON.stringify({
        event: input.type,
        outcome: input.outcome,
        person_id: input.personId,
        session_id: input.sessionId,
        request_id: input.requestId,
      }),
    );
    await this.prisma.securityEvent.create({
      data: {
        id: uuidv7(),
        type: input.type,
        personId: input.personId,
        sessionId: input.sessionId,
        outcome: input.outcome,
        requestId: input.requestId,
        ipHash: input.ipHash,
        metadata: (input.metadata as Prisma.InputJsonValue | undefined) ?? undefined,
      },
    });
  }
}
