-- R11-A: CMS + Support kernel enums

CREATE TYPE "CmsContentType" AS ENUM ('ARTICLE', 'FAQ', 'KB', 'BANNER', 'LANDING', 'LEGAL_NOTICE', 'PACK_STRING');
CREATE TYPE "CmsContentStatus" AS ENUM ('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "SupportTicketStatus" AS ENUM ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED');
CREATE TYPE "SupportMessageVisibility" AS ENUM ('CUSTOMER', 'INTERNAL');
