import type { ShellNavItem } from '@world-pharma/shell-core';

export const ADMIN_NAV: ShellNavItem[] = [
  { id: 'home', label: 'Home', href: '/', audience: 'admin' },
  { id: 'catalog', label: 'Catalog', href: '/catalog', audience: 'admin' },
  { id: 'inventory', label: 'Inventory', href: '/inventory', audience: 'admin' },
  { id: 'payments', label: 'Payments', href: '/payments', audience: 'admin', permission: 'payment:read' },
  { id: 'orders', label: 'Orders', href: '/orders', audience: 'admin', permission: 'order:read' },
  { id: 'logistics', label: 'Logistics', href: '/logistics', audience: 'admin', permission: 'logistics:read' },
  { id: 'finance', label: 'Finance', href: '/finance', audience: 'admin', permission: 'finance:read' },
  { id: 'doctors', label: 'Doctors', href: '/doctors', audience: 'admin', permission: 'doctor:review' },
  { id: 'appointments', label: 'Appointments', href: '/appointments', audience: 'admin', permission: 'appointment:read' },
  { id: 'prescriptions', label: 'Prescriptions', href: '/prescriptions', audience: 'admin', permission: 'prescription:read' },
  { id: 'video-sessions', label: 'Video sessions', href: '/video-sessions', audience: 'admin', permission: 'video:read' },
  { id: 'identity', label: 'Identity', href: '/identity', audience: 'admin', permission: 'identity:audit_read' },
  { id: 'organizations', label: 'Organizations', href: '/organizations', audience: 'admin', permission: 'partner:manage' },
  { id: 'partners', label: 'Partners', href: '/partners', audience: 'admin', permission: 'partner:manage' },
  { id: 'countries', label: 'Countries', href: '/countries', audience: 'admin', permission: 'policy:read' },
  { id: 'regions', label: 'Regions', href: '/regions', audience: 'admin', permission: 'policy:read' },
  { id: 'legal-entities', label: 'Legal entities', href: '/legal-entities', audience: 'admin', permission: 'finance:read' },
  { id: 'business-units', label: 'Business units', href: '/business-units', audience: 'admin', permission: 'policy:read' },
  { id: 'audit', label: 'Audit', href: '/audit', audience: 'admin', permission: 'identity:audit_read' },
  {
    id: 'health-consents',
    label: 'Health consents',
    href: '/governance/health/consents',
    audience: 'admin',
    permission: 'clinical:audit:read',
  },
  {
    id: 'health-access-audits',
    label: 'Health access audits',
    href: '/governance/health/access-audits',
    audience: 'admin',
    permission: 'clinical:audit:read',
  },
  {
    id: 'break-glass',
    label: 'Break-glass',
    href: '/governance/health/break-glass',
    audience: 'admin',
    permission: 'security:break_glass',
  },
  {
    id: 'care-nav-governance',
    label: 'Care navigation',
    href: '/governance/care-nav',
    audience: 'admin',
    permission: 'care_nav:audit:read',
  },
  {
    id: 'cms',
    label: 'CMS',
    href: '/cms',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'support',
    label: 'Support Desk',
    href: '/support',
    audience: 'admin',
    permission: 'support:read',
  },
  {
    id: 'crm',
    label: 'CRM',
    href: '/crm',
    audience: 'admin',
    permission: 'crm:read',
  },
  {
    id: 'marketing',
    label: 'Marketing',
    href: '/marketing',
    audience: 'admin',
    permission: 'campaign:read',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    href: '/analytics',
    audience: 'admin',
    permission: 'analytics:read',
  },
  {
    id: 'promo',
    label: 'Promo',
    href: '/promo',
    audience: 'admin',
    permission: 'promo:read',
  },
  {
    id: 'affiliates',
    label: 'Affiliates',
    href: '/affiliates',
    audience: 'admin',
    permission: 'affiliate:read',
  },
  {
    id: 'reviews',
    label: 'Reviews',
    href: '/reviews',
    audience: 'admin',
    permission: 'review:moderate',
  },
  { id: 'ops', label: 'Operations', href: '/#ops', permission: 'admin:ops', audience: 'admin' },
];
