import type { ShellNavItem } from '@world-pharma/shell-core';

export const ADMIN_NAV: ShellNavItem[] = [
  { id: 'home', label: 'Dashboard', href: '/', audience: 'admin' },
  { id: 'approvals', label: 'Approvals', href: '/approvals', audience: 'admin', permission: 'policy:read' },
  { id: 'countries', label: 'Countries', href: '/countries', audience: 'admin', permission: 'policy:read' },
  {
    id: 'launch-readiness',
    label: 'Final launch readiness',
    href: '/launch-readiness',
    audience: 'admin',
    permission: 'policy:read',
  },
  {
    id: 'provider-activation',
    label: 'Provider activation',
    href: '/provider-activation',
    audience: 'admin',
    permission: 'policy:read',
  },
  { id: 'security', label: 'Account & security', href: '/security', audience: 'admin' },
  { id: 'storefront', label: 'Storefront', href: '/storefront', audience: 'admin' },
  { id: 'catalog', label: 'Catalog', href: '/catalog', audience: 'admin', permission: 'catalog:admin' },
  { id: 'inventory', label: 'Inventory', href: '/inventory', audience: 'admin', permission: 'inventory:read' },
  { id: 'payments', label: 'Payments', href: '/payments', audience: 'admin', permission: 'payment:read' },
  { id: 'orders', label: 'Orders', href: '/orders', audience: 'admin', permission: 'order:read' },
  { id: 'logistics', label: 'Logistics', href: '/logistics', audience: 'admin', permission: 'logistics:read' },
  { id: 'finance', label: 'Finance', href: '/finance', audience: 'admin', permission: 'finance:read' },
  { id: 'marketplace', label: 'Marketplace', href: '/marketplace', audience: 'admin', permission: 'partner:manage' },
  { id: 'delivery', label: 'Delivery', href: '/delivery', audience: 'admin', permission: 'logistics:manage' },
  { id: 'search', label: 'Search index', href: '/search', audience: 'admin', permission: 'search:admin' },
  { id: 'doctors', label: 'Doctors', href: '/doctors', audience: 'admin', permission: 'doctor:review' },
  {
    id: 'healthcare-network',
    label: 'Healthcare network',
    href: '/healthcare-network',
    audience: 'admin',
    permission: 'policy:read',
  },
  { id: 'labs', label: 'Labs', href: '/labs', audience: 'admin', permission: 'lab:review' },
  { id: 'imaging', label: 'Imaging', href: '/imaging', audience: 'admin', permission: 'partner:manage' },
  { id: 'appointments', label: 'Appointments', href: '/appointments', audience: 'admin', permission: 'appointment:read' },
  { id: 'prescriptions', label: 'Prescriptions', href: '/prescriptions', audience: 'admin', permission: 'prescription:read' },
  { id: 'video-sessions', label: 'Video sessions', href: '/video-sessions', audience: 'admin', permission: 'video:read' },
  { id: 'refills', label: 'Refills', href: '/refills', audience: 'admin', permission: 'prescription:read' },
  { id: 'dispensing', label: 'Dispensing', href: '/dispensing', audience: 'admin', permission: 'prescription:read' },
  { id: 'care-plans', label: 'Care plans', href: '/care-plans', audience: 'admin', permission: 'loyalty:read' },
  { id: 'health-packages', label: 'Health packages', href: '/health-packages', audience: 'admin', permission: 'lab:review' },
  { id: 'speciality-care', label: 'Speciality care', href: '/speciality-care', audience: 'admin', permission: 'doctor:review' },
  { id: 'corporate', label: 'Corporate wellness', href: '/corporate', audience: 'admin', permission: 'partner:manage' },
  { id: 'substitutes', label: 'Substitutes', href: '/substitutes', audience: 'admin', permission: 'catalog:admin' },
  { id: 'serviceability', label: 'Serviceability', href: '/serviceability', audience: 'admin', permission: 'logistics:read' },
  { id: 'store-locator', label: 'Store locator', href: '/store-locator', audience: 'admin', permission: 'inventory:read' },
  { id: 'identity', label: 'Identity', href: '/identity', audience: 'admin', permission: 'identity:audit_read' },
  {
    id: 'company-authority',
    label: 'Company authority',
    href: '/company-authority',
    audience: 'admin',
    permission: 'rbac:grant_company',
  },
  { id: 'policy-packs', label: 'Policy packs', href: '/policy-packs', audience: 'admin', permission: 'policy:read' },
  { id: 'organizations', label: 'Organizations', href: '/organizations', audience: 'admin', permission: 'partner:manage' },
  { id: 'partners', label: 'Partners', href: '/partners', audience: 'admin', permission: 'partner:manage' },
  { id: 'regions', label: 'Regions', href: '/regions', audience: 'admin', permission: 'policy:read' },
  { id: 'legal-entities', label: 'Legal entities', href: '/legal-entities', audience: 'admin', permission: 'finance:read' },
  { id: 'business-units', label: 'Business units', href: '/business-units', audience: 'admin', permission: 'policy:read' },
  { id: 'audit', label: 'Audit', href: '/audit', audience: 'admin', permission: 'identity:audit_read' },
  {
    id: 'reliability',
    label: 'Reliability',
    href: '/reliability',
    audience: 'admin',
    permission: 'policy:read',
  },
  {
    id: 'health-consents',
    label: 'Health consents',
    href: '/governance/health/consents',
    audience: 'admin',
    permission: 'clinical:audit:read',
  },
  {
    id: 'health-access-audits',
    label: 'Health access audits',
    href: '/governance/health/access-audits',
    audience: 'admin',
    permission: 'clinical:audit:read',
  },
  {
    id: 'break-glass',
    label: 'Break-glass',
    href: '/governance/health/break-glass',
    audience: 'admin',
    permission: 'security:break_glass',
  },
  {
    id: 'care-nav-governance',
    label: 'Care navigation',
    href: '/governance/care-nav',
    audience: 'admin',
    permission: 'care_nav:audit:read',
  },
  {
    id: 'cms',
    label: 'CMS',
    href: '/cms',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'cms-blog',
    label: 'Blog',
    href: '/cms/blog',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'cms-legal',
    label: 'Legal pages',
    href: '/cms/legal',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'cms-faq',
    label: 'FAQ',
    href: '/cms/faq',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'cms-health',
    label: 'Health education',
    href: '/cms/health',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'cms-pages',
    label: 'Company pages',
    href: '/cms/pages',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'cms-media',
    label: 'CMS media',
    href: '/cms/media',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'seo',
    label: 'SEO',
    href: '/seo',
    audience: 'admin',
    permission: 'cms:read',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    href: '/notifications',
    audience: 'admin',
  },
  {
    id: 'support',
    label: 'Support Desk',
    href: '/support',
    audience: 'admin',
    permission: 'support:read',
  },
  {
    id: 'crm',
    label: 'CRM',
    href: '/crm',
    audience: 'admin',
    permission: 'crm:read',
  },
  {
    id: 'crm-automation',
    label: 'CRM automations',
    href: '/crm/automation',
    audience: 'admin',
    permission: 'crm:read',
  },
  {
    id: 'marketing',
    label: 'Marketing',
    href: '/marketing',
    audience: 'admin',
    permission: 'campaign:read',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    href: '/analytics',
    audience: 'admin',
    permission: 'analytics:read',
  },
  {
    id: 'promo',
    label: 'Promo',
    href: '/promo',
    audience: 'admin',
    permission: 'promo:read',
  },
  {
    id: 'loyalty',
    label: 'Loyalty',
    href: '/loyalty',
    audience: 'admin',
    permission: 'loyalty:read',
  },
  {
    id: 'affiliates',
    label: 'Affiliates',
    href: '/affiliates',
    audience: 'admin',
    permission: 'affiliate:read',
  },
  {
    id: 'reviews',
    label: 'Reviews',
    href: '/reviews',
    audience: 'admin',
    permission: 'review:moderate',
  },
];
