import { defineConfig, devices } from '@playwright/test';

/**
 * Sprint 38 — minimal Playwright harness for web-customer only.
 *
 * Start dependencies first (or use nx run web-customer:browser-test after):
 *   - API on :4000 with AUTH_DEV_REVEAL_OTP=true and DEV_SANDBOX_SEED=true
 *   - Next web-customer on :3000 (rewrites /api → API)
 *
 * Exact command:
 *   npx nx run web-customer:browser-test
 *   # or: node tools/playwright-harness/node_modules/@playwright/test/cli.js test -c playwright.config.ts
 */
const baseURL = process.env.WP_CUSTOMER_BASE_URL ?? 'http://127.0.0.1:3000';

export default defineConfig({
  globalSetup: './e2e/global-setup.ts',
  testDir: './src/__tests__',
  testMatch: [
    '**/customer-browser-real-use.spec.ts',
    '**/s52-real-user-ux.spec.ts',
    '**/s52-portal-shells.spec.ts',
    '**/s53-commerce-journey.spec.ts',
    '**/s53-operator-portals.spec.ts',
    '**/s54-customer-journey.spec.ts',
    '**/s54-operator-portals.spec.ts',
    '**/s55-healthcare-workflows.spec.ts',
    '**/s55-operator-workflows.spec.ts',
    '**/s56-clinical-fulfillment.spec.ts',
    '**/s56-operator-clinical.spec.ts',
    '**/s57-pathologist-lab.spec.ts',
    '**/s57-imaging-radiologist.spec.ts',
    '**/s57-vendor-fulfillment.spec.ts',
    '**/s57-cross-auth-responsive.spec.ts',
    '**/s58-marketplace-experience.spec.ts',
    '**/s59-public-experience.spec.ts',
    '**/s60-admin-control-plane.spec.ts',
    '**/s61-partner-operations.spec.ts',
    '**/s62-production-readiness.spec.ts',
    '**/s63-final-launch-gate.spec.ts',
    '**/s64-provider-activation.spec.ts',
    '**/s65-payment-provider.spec.ts',
    '**/s66-otp-messaging.spec.ts',
    '**/s67-carrier.spec.ts',
    '**/s68-erx.spec.ts',
    '**/s69-video.spec.ts',
    '**/s70-pacs.spec.ts',
    '**/s71-payout.spec.ts',
    '**/s72-kyc.spec.ts',
    '**/s73-storage.spec.ts',
    '**/s74-backup.spec.ts',
    '**/s75-observability.spec.ts',
    '**/s76-otp-messaging.spec.ts',
    '**/s77-carrier.spec.ts',
    '**/s78-erx.spec.ts',
    '**/s79-video.spec.ts',
    '**/s80-pacs.spec.ts',
    '**/s81-kyc.spec.ts',
    '**/s82-storage.spec.ts',
    '**/s83-dr.spec.ts',
    '**/s84-observability.spec.ts',
    '**/s85-payment.spec.ts',
    '**/s86-communications.spec.ts',
    '**/s87-launch-control.spec.ts',
    '**/s88-psp.spec.ts',
    '**/s89-communications.spec.ts',
    '**/s90-carrier.spec.ts',
    '**/s91-erx.spec.ts',
    '**/s92-video.spec.ts',
    '**/s93-pacs.spec.ts',
    '**/s94-kyc.spec.ts',
    '**/s95-storage.spec.ts',
    '**/s96-dr.spec.ts',
    '**/s97-observability.spec.ts',
    '**/s98-secrets-env.spec.ts',
    '**/s99-deployment.spec.ts',
    '**/s100-onboarding.spec.ts',
    '**/s101-foundation.spec.ts',
    '**/s102-psp.spec.ts',
    '**/s103-communications.spec.ts',
    '**/s105-carrier.spec.ts',
    '**/s106-kyc.spec.ts',
    '**/s107-storage.spec.ts',
    '**/s108-backup.spec.ts',
    '**/s109-observability.spec.ts',
    '**/s110-security.spec.ts',
    '**/s111-pentest.spec.ts',
    '**/s112-foundation.spec.ts',
    '**/s113-abuse.spec.ts',
    '**/s114-edge.spec.ts',
    '**/s115-input.spec.ts',
    '**/s116-security-gate.spec.ts',
    '**/s117-foundation-prep.spec.ts',
    '**/s118-release-eng.spec.ts',
    '**/s119-deploy-target.spec.ts',
    '**/s120-psp.spec.ts',
    '**/s121-comms.spec.ts',
    '**/s122-carrier.spec.ts',
    '**/s123-vendor.spec.ts',
    '**/s124-kyc.spec.ts',
    '**/s125-consultation-erx.spec.ts',
    '**/s126-lab-diagnostics.spec.ts',
    '**/s127-lab-partner-onboarding.spec.ts',
    '**/s128-psp-activation-control.spec.ts',
  ],
  outputDir: './test-results/playwright',
  timeout: 180_000,
  expect: { timeout: 20_000 },
  fullyParallel: false,
  workers: 1,
  retries: process.env.CI ? 1 : 0,
  reporter: [['list']],
  use: {
    baseURL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'off',
    actionTimeout: 20_000,
    navigationTimeout: 45_000,
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
